### ISSUE TITLE
ASTConsumer.cpp does not seem to be clang-3.5 compatible

### ISSUE THREAD

**Issue by tahsinH** [hiraditya/cpp2cxx#1]
First of kudos on the library. 
I see , there were some updates for enabling the library to be built with clang-3.5.
So I downloaded llvm+clang 3.5 , but failed to build the library. 
It went 75% before failing to compile at ASTConsumer.cpp.

/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp: In member function ‘int MyASTConsumer::InitializeCI(clang::CompilerInstance&, const std::vectorstd::basic_string<char >&)’:
/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:99:76: error: no matching function for call to ‘clang::TargetInfo::CreateTargetInfo(clang::DiagnosticsEngine&, clang::TargetOptions_)’
/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:99:76: note: candidate is:
In file included from /tmp/cpp2cxx-master/ClangInterface/ASTConsumer.hpp:16:0,
                 from /tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:1:
/usr/lib/llvm-3.5/include/clang/Basic/TargetInfo.h:98:3: note: static clang::TargetInfo_ clang::TargetInfo::CreateTargetInfo(clang::DiagnosticsEngine&, const std::shared_ptrclang::TargetOptions&)
/usr/lib/llvm-3.5/include/clang/Basic/TargetInfo.h:98:3: note:   no known conversion for argument 2 from ‘clang::TargetOptions_’ to ‘const std::shared_ptrclang::TargetOptions&’
/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:467:61: error: invalid initialization of reference of type ‘const clang::FrontendOptions&’ from expression of type ‘clang::HeaderSearchOptions’
In file included from /usr/lib/llvm-3.5/include/clang/Frontend/CompilerInstance.h:16:0,
                 from /tmp/cpp2cxx-master/ClangInterface/TrackMacro.hpp:9,
                 from /tmp/cpp2cxx-master/ClangInterface/ASTConsumer.hpp:5,
                 from /tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:1:
/usr/lib/llvm-3.5/include/clang/Frontend/Utils.h:64:6: error: in passing argument 3 of ‘void clang::InitializePreprocessor(clang::Preprocessor&, const clang::PreprocessorOptions&, const clang::FrontendOptions&)’
/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp: In member function ‘void MyASTConsumer::DumpContent(const string&)’:
/tmp/cpp2cxx-master/ClangInterface/ASTConsumer.cpp:489:25: error: ‘class clang::SourceManager’ has no member named ‘createMainFileID’
make[2]: *_\* [ClangInterface/CMakeFiles/ASTConsumer.dir/ASTConsumer.cpp.o] Error 1

**Comment by hiraditya** [comment]
Sorry for the late reply. I'll look into it soon. If you have found the fix then please let me know.
Thanks for reporting the problem.

**Comment by hiraditya** [comment]
Please check now, it should compile with latest llvm 3.7 release.
